homepage: "https://curl.haxx.se/"
language: c++
primary_contact: "test@test.com"
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/fuzzstati0n/fuzzgoat.git'
